#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['itsdangerous']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='itsdangerous',
      version='2.2.0',
      description='Safely pass data to untrusted environments and back.',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.8',
     )
